### PR TITLE
Modified UI/UX

### PR DESCRIPTION
**Pull request by Zeeshan-2k1**
#5 Improved the ui and ux. Please review it and merge it.

### CODE REVIEW

**Comment by iampavangandhi** [comment]
@Zeeshan-2k1 I can't see UI changes from the code only. You have to describe what changes you made with screenshots of them

**Comment by Zeeshan-2k1** [comment]
@iampavangandhi OK I am attaching the screenshots.
Screenshot from 2020-10-01 18-41-46
Screenshot from 2020-10-01 18-42-02
Screenshot from 2020-10-01 18-42-30
Screenshot from 2020-10-01 18-42-09
Screenshot from 2020-10-01 18-43-53

**Comment by Zeeshan-2k1** [comment]
@iampavangandhi is this good enough?

**Comment by iampavangandhi** [comment]
@Zeeshan-2k1 What changes you made just rounded the corners? or Anything else?

**Comment by Zeeshan-2k1** [comment]
Changed the font-type, hover-effect, button-size, font size, input box improved padding and improved responsiveness.

**Comment by iampavangandhi** [comment]
@Zeeshan-2k1 Okay :+1:

**Pull request merged**
